### ISSUE TITLE
Find sequence of PPC to achieve 3rd order convergence in velocity

### ISSUE THREAD

**Issue by hlokavarapu** [EGP-CIG-REU/SECOND_PARTICLE_PAPER#146]
Details:
 - Q2xQ1
 - RK2
 - Bilinear
 - For a global refinement level of 3 and PPC of 36, L2 error of **u** = 0.061133970000000003.
   Then, to achieve 3rd order convergence, at a global ref. lvl. of 4, ideally, an L2 error of **u** =  0.00764174625 is required. Looking at the numbers, I estimate that 100 PPC is necessary.

**Comment by egpuckett** [comment]
Go for it @hlokavarapu ... You're the lead author on this paper.  So lead!

**Comment by hlokavarapu** [comment]
Based on the initial results, the L2 error of **u** is approx. 7.561530e-03 at PPC=100. So assuming that the error is similar at the end time, for a resolution of 5, ideally, an L2 error of **u** = 0.00095521828125 is required. Looking at the numbers once more, I estimate that PPC=225.

**Comment by hlokavarapu** [comment]
Stamede2 is under maintenance today. Computations are on hold till 7:30 PM CT.

**Comment by egpuckett** [comment]
Can you put what you have so far in a graph.  I'm having a difficult time visualizing convergence just given the numbers.On Sep 11, 2018 7:44 AM, Harsha Lokavarapu <notifications@github.com> wrote:Stamede2 is under maintenance today. Computations are on hold till 7:30 PM CT.

**Comment by gassmoeller** [comment]
As far as I understand it means you were able to achieve 3rd order convergence with an increasing number of PPC. Great work! If we can show it for level 5 as well, we can already write everything up while level 6 is running (I guess it might be expensive?). Either way, it would show that our understanding was correct, and we can achieve the expected convergence order only with an increasing number of PPC.

**Comment by egpuckett** [comment]
I agree with Rene's suggestion, especially finishing the write up as soon as possible so we can submit before September 30.Harsha, if you could clean up the plots as we discussed the other day and put a plot / graph of what you have computed so far as a 'place holder' so we can reference it, that would be a big step.Thanks Rene! Your insight has really helped get us moving again, with something to present that I think will be valuable to the community.- G On Sep 11, 2018 10:13 AM, Rene Gassmoeller <notifications@github.com> wrote:As far as I understand it means you were able to achieve 3rd order convergence with an increasing number of PPC. Great work! If we can show it for level 5 as well, we can already write everything up while level 6 is running (I guess it might be expensive?). Either way, it would show that our understanding was correct, and we can achieve the expected convergence order only with an increasing number of PPC.
